<?php

namespace GapaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CrossingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrossingRepository extends EntityRepository
{
}
