ugm:
    resource: "@UgmBundle/Resources/config/routing.yml"
    prefix:   /admin

gapa:
    resource: "@GapaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
